### ISSUE TITLE
BUG - OAuthException: (#200) Missing Permissions

### ISSUE THREAD

**Issue by demos77** [thephpleague/oauth2-facebook#55] opened 2020-07-17 08:12 UTC
There is an error : OAuthException: (#200) Missing Permissions

in order to fix, in this file : https://github.com/thephpleague/oauth2-facebook/blob/master/src/Provider/Facebook.php

need to remove **'cover{source}'** field

cf: https://github.com/thephpleague/oauth2-facebook/pull/54

**Comment by Dandrum** [comment] 2020-07-17 08:48
Thanks bro that helped us a lot. We just launched our page today and it bugged..

**Comment by harrieverveer** [comment] 2020-07-17 11:33
Ugh, I think this one is urgent. This morning our Facebook login suddenly stopped working because of this bug, I think because Facebook changed something to their API. I assume _all_ Facebook integrations using this bundle are failing at the moment (except when someone actually has permissions to receive the cover{source} field, which would be a very happy (and rare) coincidence).

I managed to fix it for now for our application by forking the repo. This seemed like the only option without hacking in the vendor folder, since the fields are hardcoded and I couldn't replace/decorate the Provider in Symfony. This works but it's a hassle, so I really hope PR https://github.com/thephpleague/oauth2-facebook/pull/54 gets merged soon (I can confirm it solves the issue) as it will prevent a lot of headaches around the globe.

**Comment by DraCzris** [comment] 2020-07-17 14:41
I used a solution suggested [here](https://github.com/vihuvac/recaptcha-bundle/issues/14#issuecomment-292773538).

Using [cweagans/composer-patches](https://github.com/cweagans/composer-patches) package I was able to temporarily patch the package.

Applying the following patch:

```
--- /dev/null
+++ src/Provider/Facebook.php
@@ -103,7 +103,7 @@ class Facebook extends AbstractProvider
         $fields = [
             'id', 'name', 'first_name', 'last_name',
             'email', 'hometown', 'picture.type(large){url,is_silhouette}',
-            'cover{source}', 'gender', 'locale', 'link', 'timezone', 'age_range'
+            'gender', 'locale', 'link', 'timezone', 'age_range'
         ];

         // backwards compatibility less than 2.8

```

**Comment by judev** [comment] 2020-07-17 15:57
Another option if you can't easily fork or patch the package is to extend the `Provider\Facebook` class as follows, and use it instead:

```php
<?php

use League\OAuth2\Client\Provider;
use League\OAuth2\Client\Token\AccessToken;

class FacebookUserProvider extends Provider\Facebook {
    public function getResourceOwnerDetailsUrl(AccessToken $token)
    {
        $fields = [
            'id', 'name', 'first_name', 'last_name',
            'email', 'hometown', 'picture.type(large){url,is_silhouette}',
            'cover{source}', 'gender', 'locale', 'link', 'timezone', 'age_range'
        ];

        // backwards compatibility less than 2.8
        if (version_compare(substr($this->graphApiVersion, 1), '2.8') < 0) {
            $fields[] = 'bio';
        }

        $appSecretProof = Provider\AppSecretProof::create($this->clientSecret, $token->getToken());

        return $this->getBaseGraphUrl().$this->graphApiVersion.'/me?fields='.implode(',', $fields)
                        .'&access_token='.$token.'&appsecret_proof='.$appSecretProof;
    }

    private function getBaseGraphUrl()
    {
        return static::BASE_GRAPH_URL;
    }
}
```

**Comment by madmatt** [comment] 2020-07-20 21:54
Until this is resolved, there is an open pull requests that fixes the issue: see #59.

**Comment by therealmikz** [comment] 2020-07-21 10:55
More on @judev - after extending a class, the least intrusive way to replace the provider is to create container compiler pass:

```php
<?php

namespace App\Infrastructure\DependencyInjection\Compiler;

use App\Infrastructure\Oauth\Provider\FacebookUserProvider;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

class FacebookCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $definition = $container->getDefinition('knpu.oauth2.provider.facebook');
        $definition->replaceArgument(0, FacebookUserProvider::class);
    }
}
```

and register it in kernel (`configureContainer` method of Kernel class):

```php
<?php

$container->addCompilerPass(new FacebookCompilerPass(), PassConfig::TYPE_BEFORE_OPTIMIZATION);
```

**Comment by H4wKs** [comment] 2020-07-22 09:43
Thanks @therealmikz for this additional information, because I'am personally not familiar yet with the SF decoration / definition and compiler pass feature, and it took me quite time to figure this out by myself, and it would for sure have helped me having that info when I was looking into it. I think this is probably the best get around in the meantime for those using SF

However, if it could help, here is another solution of how I manage to fix this

- Fork the league/oauth2-facebook repo in my own Github
- Patched the Facebook provider as @mikealmond suggested & commit on the master of my personal Github repository
- Updated my composer following this https://getcomposer.org/doc/05-repositories.md#vcs
"repositories": [ { "type": "vcs", "url": "https://github.com/h4wks/oauth2-facebook" } ],
And changed:
"require": { "league/oauth2-facebook": "^2.0" }
By
"require": { "league/oauth2-facebook": "dev-master" }

- Run composer update.

If you choose to go this way, I strongly recommend you to replace the URL by your own repository as I am not going to maintain that one, it's just a temporarily get around.

**Comment by Blackskyliner** [comment] 2020-08-05 07:11
Changes are live as of 2.0.2 so this issue could be closed I guess?

**Closed** 2020-08-05 11:26 UTC
